spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5440}/${POSTGRES_DB:api_lang_arena}
    username: ${POSTGRES_USER:api_lang_user}
    password: ${POSTGRES_PASSWORD:api_lang_password}
    hikari:
      maximum-pool-size: ${KT_DB_MAX_POOL_SIZE:10}
      minimum-idle: ${KT_DB_MIN_IDLE:2}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

app:
  messaging:
    bill-created-queue: ${RABBITMQ_BILL_CREATED_QUEUE:bill-created}
